site_name: Team Tasks Manager
theme:
  favicon: assets/images/favicon.ico
  logo: assets/nextlevel-icon.png
  font:
    text: Montserrat
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: light blue
      accent: light blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: blue

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/5HWx3JR
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nextlevelitalia/

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true    
      
site_description: Team Tasks Manager is the checklist designed to take your team coordination to the next level!
copyright: |
  &copy; 2024 <a href="https://www.linkedin.com/company/nextlevelitalia"  target="_blank" rel="noopener">Next Level Italia S.A.S.</a>